version: 2

updates:
  # npm
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

    groups:
      prd-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
