baseurl = "https://www.rhpav7.com"
languageCode = "ja-jp"
title = ".umirc"
Paginate = 50 # Number of posts per page
enableRobotsTXT = true
hasCJKLanguage = true
canonifyURLs = true
enableEmoji = true
enableGitInfo = true
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "Jan 2, 2006 3:04PM"
author = "shiomiya"
images = ["img/ogp.png"]

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = ".umirc" # Title for home page
description = "Tech, Games and Gadgets"
related = true # Includes related articles at the bottom of the article
taxonomiesCount = true # Add taxonomies count

[params.social]
github = "shiomiyan"
rss = "index.xml"

[params.social.config]
platforms = ["rss"]

[taxonomies]
tag = "tags"
category = "categories"

[blackfriday]
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe = true
