baseurl = "https://www.shiomiya.com"
languageCode = "ja-jp"
title = "umilog"
copyright = "&copy; shiomiya 2019"
googleAnalytics = "UA-139120340-2"
Paginate = 10 # Number of posts per page
enableRobotsTXT = true
hasCJKLanguage = true
canonifyURLs = true
enableEmoji = true
enableGitInfo = true
pygmentsUseClasses = true
pygmentsCodefences = true

[permalinks]
posts = "/:filename"

[params]
copyrightYear = 2019
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "Jan 2, 2006 3:04PM"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "umilog" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.social]
github = "shiomiyan"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","rss"]

[params.sections_right]
"/about" = "about"
"/categories" = "categories"

[taxonomies]
tag ="tags"
category = "categories"

[blackfriday]
hrefTargetBlank = true
