name = "blog"
compatibility_date = "2025-03-04"

compatibility_flags = ["nodejs_compat"]

[vars]
FUNCTIONS_CORS_ORIGIN = "https://blog.736b.moe"
GITHUB_CLIENT_ID = "Ov23liETvAjVf2DK62Bl"
ALLOWED_DOMAINS = "blog.736b.moe"

[secrets]
required = ["GITHUB_CLIENT_SECRET"]

[[routes]]
pattern = "blog.736b.moe"
custom_domain = true

[[kv_namespaces]]
binding = "BLOG_736B_MOE_UPVOTE_COUNTER"
id = "1839db5b272840018387728603b94304"

[dev]
port = 4321

[observability]
enabled = true

[observability.logs]
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 0.01
