# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: shiomiyan/blog
  base_url: https://blog.736b.moe/admin
  auth_endpoint: auth
  auth_scope: public_repo
  allow_token_auth: false
  skip_ci: true

media_folder: /public/media
public_folder: /media

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: /src/content/posts
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    format: yaml-frontmatter
    extension: md
    preview_path: "/posts/{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: description,
          label: Description,
          widget: text,
          required: false,
          default: "",
        }
      - { name: created, label: Date, widget: datetime, default: "{{datetime}}" }
      - { name: draft, label: Draft, widget: boolean, default: true }
      - { name: id, label: ID, widget: uuid }
      - name: category
        label: Category
        widget: select
        default: diary
        options:
          - { label: Tech, value: tech }
          - { label: Diary, value: diary }
      - name: tags
        label: Tags
        widget: select
        multiple: true
        default: []
        options:
          - { label: セキュリティ, value: security }
          - { label: 雑記, value: random }
          - { label: Tree-sitter, value: tree-sitter }
          - { label: Astro, value: astro }
          - { label: Cloudflare, value: cloudflare }
          - { label: Raspberry Pi, value: raspberry-pi }
          - { label: Puppeteer, value: puppeteer }
          - { label: TypeScript, value: typescript }
          - { label: Deno, value: deno }
          - { label: npm, value: npm }
          - { label: rollup, value: rollup }
          - { label: Browser, value: browser }
          - { label: RFC, value: rfc }
          - { label: Site updates, value: site-updates }
          - { label: Weekly report, value: weekly-report }
      - { name: body, label: Body, widget: markdown }
