name: reviewdog
on:
  push:
    branches:
      - master

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node/npm
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: textlint-github-pr-check
        uses: tsuyoshicho/action-textlint@v2
        with:
          github_token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          reporter: github-pr-check
          textlint_flags: "content/**/*.md"
      - name: textlint-github-check
        uses: tsuyoshicho/action-textlint@v2
        with:
          github_token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          reporter: github-check
          textlint_flags: "content/**/*.md"
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v2
        with:
          github_token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          reporter: github-pr-review
          textlint_flags: "content/**/*.md"
      - name: create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Document editing with textlint.
          labels: Auto PR
          branch: textlint
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}