name: reviewdog
on:
  push:
    branches:
      - master

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node/npm
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: npm install
        run: npm install
      - name: Fix with textlint
        run: npm run fix
      - name: create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Document editing with textlint.
          labels: Auto PR
          branch: textlint
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}