name: textlint
on: [pull_request]

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          textlint_flags: "articles/**"
